[tool.pip]
name="join_together"
version = "0.1.0"
description = "Social network by Django"
authors = ["bkalika"]

[tool.pip.dependencies]
python = "3.8"
django = "^3.1.2"
djangorestframework = "^3.12.1"
pillow = "^8.0.1"
psycopg2 = "^2.8.6"
djoser = "^2.1.0"
